# Generated by Django 5.1.4 on 2025-01-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0036_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification3',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Notification1',
        ),
        migrations.DeleteModel(
            name='Notification2',
        ),
        migrations.DeleteModel(
            name='Notification3',
        ),
    ]
