# Generated by Django 5.1.4 on 2025-01-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0037_remove_notification1_user_remove_notification2_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proctoringsession',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proctoringevent',
            name='session',
        ),
        migrations.RemoveField(
            model_name='proctoringevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proctoringsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamParticipant',
        ),
        migrations.DeleteModel(
            name='ProctoringEvent',
        ),
        migrations.DeleteModel(
            name='ProctoringSession',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
