# Generated by Django 5.1.4 on 2025-01-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyincharge',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
