# Generated by Django 5.1.4 on 2025-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_url',
            field=models.URLField(default='https://example.com/default-file-url', max_length=500),
        ),
    ]
